name: Sonar Cloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: gradlew build

      - name: Sonar Cloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          gradlew sonarqube \
            -Dsonar.organization=Carlos.Moreno27@alu.uclm.es \
            -Dsonar.projectKey=BEERUTE_REPOSITORIO \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.scanner.distribution=SonarScanner
